import customtkinter as ctk

class LeftPanel(ctk.CTkFrame):
    def __init__(self, master, toggle_cmd, workspace=None, **kwargs):
        super().__init__(master, width=250, corner_radius=0, fg_color="#2b2b2b", **kwargs)
        self.workspace = workspace
        
        # --- 1. CLOSE BUTTON ---
        self.close_btn = ctk.CTkButton(
            self, text="<", width=20, height=60, 
            fg_color="#3d3d3d", command=toggle_cmd
        )
        self.close_btn.place(relx=1.0, rely=0.5, anchor="e")
        
        # --- 2. FACILITY FILTER SECTION ---
        self.filter_frame = ctk.CTkFrame(self, fg_color="transparent")
        self.filter_frame.pack(fill="x", padx=10, pady=10)
        
        ctk.CTkLabel(
            self.filter_frame, text="FACILITIES", 
            font=("Arial", 11, "bold"), text_color="gray"
        ).pack(anchor="w", padx=10, pady=(0, 5))

        # This sub-frame will hold the actual checkboxes generated by FilterLogic
        self.checkbox_container = ctk.CTkFrame(self.filter_frame, fg_color="transparent")
        self.checkbox_container.pack(fill="x")

        # --- 3. ACTIONS SECTION ---
        self.action_frame = ctk.CTkFrame(self, fg_color="transparent")
        self.action_frame.pack(fill="x", padx=10, pady=20)

        self.route_btn = ctk.CTkButton(
            self.action_frame, 
            text="Route facilities", 
            height=40,
            fg_color="#1f538d",
            hover_color="#14375e",
            command=self.open_routing
        )
        self.route_btn.pack(fill="x", padx=10)

    def setup_filters(self):
        """Clears container and asks FilterLogic to build the UI elements."""
        # Clear existing widgets to avoid duplicates
        for widget in self.checkbox_container.winfo_children():
            widget.destroy()

        # Delegate the actual loop and checkbox creation to the logic engine
        if self.workspace and hasattr(self.workspace, 'filter_engine'):
            self.workspace.filter_engine.build_filter_ui(self.checkbox_container)

    def open_routing(self):
        """Calls the routing manager window."""
        if self.workspace and hasattr(self.workspace, 'routing_engine'):
            self.workspace.routing_engine.open_route_window(self.workspace.all_data)